### ISSUE TITLE
Tilix 1.7.9 fails to build on openSUSE Tumbleweed (multiple undefined references when linking)

### ISSUE THREAD

**Issue by sogalboogalsky** [gnunn1/tilix#1389]
Hi,
When building the latest release of Tilix for openSUSE, it fails at linking step, outputting a lot of "undefined reference to ***" warnings.
The build log can be found here: https://gist.github.com/sogalboogalsky/aa1c2887168eba4cc0d197d896a39200

Note that Tilix 1.7.9 builds correctly on openSUSE Leap 42.3 and the upcoming 15.0. I assume this is a problem with Tumbleweed (some checks in compiler or deprecation somewhere), I just need some help to understand the nature of the problem so that I can fix it in specfile or with a patch.

Thanks.
