### ISSUE TITLE
Cannot compile with GtkD 1.7.0

### ISSUE THREAD

**Issue by dsboger** [gnunn1/tilix#1152]
I think GtkD made some restructuring of the source code (https://github.com/gtkd-developers/GtkD/commit/2c5c50977812daa6af4769c7ef2eb054e26c5dd4 and maybe others) and Tilix fails to compile with the following error:

```
source/gx/tilix/terminal/terminal.d(45): Error: module File is in file 'gio/File.d' which cannot be read
```

I've tried to solve the given message, by changing the offending line to 

```
45       import gio.FileT : GFile = GFile;
```

and the message went away, only to be replaced by the following ones:

```
source/gx/tilix/terminal/exvte.d(242): Error: cannot implicitly override base class method vte.Terminal.Terminal.getAllowHyperlink with gx.tilix.terminal.exvte.ExtendedVTE.getAllowHyperlink; add 'override' attribute
source/gx/tilix/terminal/exvte.d(246): Error: cannot implicitly override base class method vte.Terminal.Terminal.setAllowHyperlink with gx.tilix.terminal.exvte.ExtendedVTE.setAllowHyperlink; add 'override' attribute
source/gx/tilix/terminal/exvte.d(250): Error: cannot implicitly override base class method vte.Terminal.Terminal.hyperlinkCheckEvent with gx.tilix.terminal.exvte.ExtendedVTE.hyperlinkCheckEvent; add 'override' attribute
source/secret/Prompt.d(66): Error: function secret.Prompt.Prompt.setStruct does not override any function, did you mean to override 'gio.DBusProxy.DBusProxy.getStruct'?
source/secret/Service.d(72): Error: function secret.Service.Service.setStruct does not override any function, did you mean to override 'gio.DBusProxy.DBusProxy.getStruct'?
source/secret/Collection.d(69): Error: function secret.Collection.Collection.setStruct does not override any function, did you mean to override 'gio.DBusProxy.DBusProxy.getStruct'?
source/secret/Item.d(71): Error: function secret.Item.Item.setStruct does not override any function, did you mean to override 'gio.DBusProxy.DBusProxy.getStruct'?
```

That's as far as my knowledge goes with D and GtkD. Let me know if I can provide any more info. And thanks again for your efforts!

**Comment by gnunn1** [comment]
The problem is I added getAllowHyperlink on my own to the exvte class which inherits from GtkDs terminal class. I need to add some sort of version check around that code and only compile it in for older versions of GTKD.
