### ISSUE TITLE
Can not compile on debian 9.0

### ISSUE THREAD

**Issue by toplinuxsir** [gnunn1/tilix#1011]
dub build --build=release

Fetching gtk-d 3.5.1 (getting selected version)...
Performing "release" build using gdc for x86_64.
gtk-d:gtkd 3.5.1: building configuration "library"...
gtk-d:gstreamer 3.5.1: building configuration "library"...
gtk-d:gtkdgl 3.5.1: building configuration "library"...
gtk-d:peas 3.5.1: building configuration "library"...
gtk-d:sv 3.5.1: building configuration "library"...
gtk-d:vte 3.5.1: building configuration "library"...
gtk-d 3.5.1: building configuration "library"...
tilix ~master: building configuration "default"...
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(48, "source/app.d", "app.main", "int app.main(string[] args)", "app", string, Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(48, "source/app.d", "app.main", "int app.main(string[] args)", "app", string, Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/app.d:48:14: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(48, "source/app.d", "app.main", "int app.main(string[] args)", "app", string, Exception) error instantiating
         error("Unexpected error occurred", e);
              ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(1393, "source/gx/tilix/appwindow.d", "gx.tilix.appwindow.AppWindow.loadSession", "void gx.tilix.appwindow.AppWindow.loadSession()", "gx.tilix.appwindow", Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(1393, "source/gx/tilix/appwindow.d", "gx.tilix.appwindow.AppWindow.loadSession", "void gx.tilix.appwindow.AppWindow.loadSession()", "gx.tilix.appwindow", Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/appwindow.d:1393:22: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(1393, "source/gx/tilix/appwindow.d", "gx.tilix.appwindow.AppWindow.loadSession", "void gx.tilix.appwindow.AppWindow.loadSession()", "gx.tilix.appwindow", Exception) error instantiating
                 error(e);
                      ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(223, "source/gx/tilix/bookmark/bmtreeview.d", "gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived", "void gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived(DragContext dc, int x, int y, SelectionData data, uint info, uint time, Widget widget)", "gx.tilix.bookmark.bmtreeview", Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(223, "source/gx/tilix/bookmark/bmtreeview.d", "gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived", "void gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived(DragContext dc, int x, int y, SelectionData data, uint info, uint time, Widget widget)", "gx.tilix.bookmark.bmtreeview", Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/bookmark/bmtreeview.d:223:18: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(223, "source/gx/tilix/bookmark/bmtreeview.d", "gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived", "void gx.tilix.bookmark.bmtreeview.BMTreeView.onDragDataReceived(DragContext dc, int x, int y, SelectionData data, uint info, uint time, Widget widget)", "gx.tilix.bookmark.bmtreeview", Exception) error instantiating
             error(e);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(234, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.FolderBookmark.deserialize", "void gx.tilix.bookmark.manager.FolderBookmark.deserialize(JSONValue value)", "gx.tilix.bookmark.manager", Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(234, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.FolderBookmark.deserialize", "void gx.tilix.bookmark.manager.FolderBookmark.deserialize(JSONValue value)", "gx.tilix.bookmark.manager", Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/bookmark/manager.d:234:22: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(234, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.FolderBookmark.deserialize", "void gx.tilix.bookmark.manager.FolderBookmark.deserialize(JSONValue value)", "gx.tilix.bookmark.manager", Exception) error instantiating
                 error(e);
                      ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(616, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.BookmarkManager.load", "void gx.tilix.bookmark.manager.BookmarkManager.load()", "gx.tilix.bookmark.manager", Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(616, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.BookmarkManager.load", "void gx.tilix.bookmark.manager.BookmarkManager.load()", "gx.tilix.bookmark.manager", Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/bookmark/manager.d:616:22: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(616, "source/gx/tilix/bookmark/manager.d", "gx.tilix.bookmark.manager.BookmarkManager.load", "void gx.tilix.bookmark.manager.BookmarkManager.load()", "gx.tilix.bookmark.manager", Exception) error instantiating
                 error(e);
                      ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(903, "source/gx/tilix/prefeditor/prefdialog.d", "gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels", "void gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels()", "gx.tilix.prefeditor.prefdialog", string, XMLException).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(903, "source/gx/tilix/prefeditor/prefdialog.d", "gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels", "void gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels()", "gx.tilix.prefeditor.prefdialog", string, XMLException).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/prefeditor/prefdialog.d:903:18: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(903, "source/gx/tilix/prefeditor/prefdialog.d", "gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels", "void gx.tilix.prefeditor.prefdialog.ShortcutPreferences.loadLocalizedShortcutLabels()", "gx.tilix.prefeditor.prefdialog", string, XMLException) error instantiating
             error("Failed to parse shortcuts.ui", e);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(1053, "source/gx/tilix/session.d", "gx.tilix.session.Session.initSession", "void gx.tilix.session.Session.initSession(JSONValue value, string filename, int width, int height, bool firstRun)", "gx.tilix.session", string, Exception).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)128u.logImpl!(1053, "source/gx/tilix/session.d", "gx.tilix.session.Session.initSession", "void gx.tilix.session.Session.initSession(JSONValue value, string filename, int width, int height, bool firstRun)", "gx.tilix.session", string, Exception).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/session.d:1053:18: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)128u.defaultLogFunction!(1053, "source/gx/tilix/session.d", "gx.tilix.session.Session.initSession", "void gx.tilix.session.Session.initSession(JSONValue value, string filename, int width, int height, bool firstRun)", "gx.tilix.session", string, Exception) error instantiating
             error("Session could not be created due to error", e);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/logger/core.d:487:44: error: safe function 'std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)96u.defaultLogFunction!(3256, "source/gx/tilix/terminal/terminal.d", "gx.tilix.terminal.terminal.Terminal.isProcessRunning", "bool gx.tilix.terminal.terminal.Terminal.isProcessRunning(out string name)", "gx.tilix.terminal.terminal", FileException).defaultLogFunction' cannot call system function 'std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)96u.logImpl!(3256, "source/gx/tilix/terminal/terminal.d", "gx.tilix.terminal.terminal.Terminal.isProcessRunning", "bool gx.tilix.terminal.terminal.Terminal.isProcessRunning(out string name)", "gx.tilix.terminal.terminal", FileException).logImpl'
                 prettyFuncName, moduleName)(args);
                                            ^
source/gx/tilix/terminal/terminal.d:3256:20: error: template instance std.experimental.logger.core.defaultLogFunction!cast(LogLevel)cast(ubyte)96u.defaultLogFunction!(3256, "source/gx/tilix/terminal/terminal.d", "gx.tilix.terminal.terminal.Terminal.isProcessRunning", "bool gx.tilix.terminal.terminal.Terminal.isProcessRunning(out string name)", "gx.tilix.terminal.terminal", FileException) error instantiating
             warning(fe);
                    ^
source/gx/tilix/terminal/terminal.d:3635:13: error: case must be a string or an integral constant, not SETTINGS_PROFILE_TRIGGER_UPDATE_STATE_VALUE
             case SETTINGS_PROFILE_TRIGGER_UPDATE_STATE_VALUE:
             ^
source/gx/tilix/terminal/terminal.d:3638:13: error: case must be a string or an integral constant, not SETTINGS_PROFILE_TRIGGER_EXECUTE_COMMAND_VALUE
             case SETTINGS_PROFILE_TRIGGER_EXECUTE_COMMAND_VALUE:
             ^
source/gx/tilix/terminal/terminal.d:3641:13: error: case must be a string or an integral constant, not SETTINGS_PROFILE_TRIGGER_SEND_NOTIFICATION_VALUE
             case SETTINGS_PROFILE_TRIGGER_SEND_NOTIFICATION_VALUE:
             ^
source/gx/tilix/terminal/terminal.d:3644:13: error: case must be a string or an integral constant, not SETTINGS_PROFILE_TRIGGER_UPDATE_BADGE_VALUE
             case SETTINGS_PROFILE_TRIGGER_UPDATE_BADGE_VALUE:
             ^
source/gx/tilix/terminal/terminal.d:3647:13: error: case must be a string or an integral constant, not SETTINGS_PROFILE_TRIGGER_UPDATE_TITLE_VALUE
             case SETTINGS_PROFILE_TRIGGER_UPDATE_TITLE_VALUE:
             ^
gdc failed with exit code 1.

**Comment by gnunn1** [comment]
It looks like you are using GDC which Tilix isn't compatible with because it's too far behind the D specification, please use DMD or LDC to compile Tilix.
