### ISSUE TITLE
Error building 1.7.1 on Ubuntu 17.10

### ISSUE THREAD

**Issue by pat-s** [gnunn1/tilix#1210]
```
dub build --build=debug
Performing "debug" build using ldc2 for x86_64.                                                                                                                                                                                  
gtk-d:gtkd 3.7.2: target for configuration "library" is up to date.                                                                                                                                                              
gtk-d:vte 3.7.2: target for configuration "library" is up to date.                                                                                                                                                               
tilix ~master: building configuration "default"...                                                                                                                                                                               
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib7adler32FkAxvZk':                                                                                        
std/zlib.d:(.text._D3std4zlib7adler32FkAxvZk[_D3std4zlib7adler32FkAxvZk]+0x50): undefined reference to `adler32'                                                                                                                 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib5crc32FkAxvZk':                                                                                          
std/zlib.d:(.text._D3std4zlib5crc32FkAxvZk[_D3std4zlib5crc32FkAxvZk]+0x50): undefined reference to `crc32'                                                                                                                       
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib8compressFAxviZAh':                                                                                      
std/zlib.d:(.text._D3std4zlib8compressFAxviZAh[_D3std4zlib8compressFAxviZAh]+0x50): undefined reference to `compress2'                                                                                                           
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib10uncompressFAxvmiZAv':                                                                                  
std/zlib.d:(.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0xd1): undefined reference to `inflate'                                                                                                     
std/zlib.d:(.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0xe6): undefined reference to `inflateEnd'                                                                                                  
std/zlib.d:(.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0x164): undefined reference to `inflateEnd'                                                                                                 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib8Compress5errorMFiZv':                                                                                   
std/zlib.d:(.text._D3std4zlib8Compress5errorMFiZv[_D3std4zlib8Compress5errorMFiZv]+0x16): undefined reference to `deflateEnd'                                                                                                    
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib8Compress6__dtorMFZv':                                                                                   
std/zlib.d:(.text._D3std4zlib8Compress6__dtorMFZv[_D3std4zlib8Compress6__dtorMFZv]+0x18): undefined reference to `deflateEnd'                                                                                                    
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib8Compress8compressMFAxvZAxv':                                                                            
std/zlib.d:(.text._D3std4zlib8Compress8compressMFAxvZAxv[_D3std4zlib8Compress8compressMFAxvZAxv]+0xdf): undefined reference to `deflate'                                                                                         
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib8Compress5flushMFiZAv':                                                                                  
std/zlib.d:(.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0x84): undefined reference to `deflate'
std/zlib.d:(.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0xe1): undefined reference to `deflate'
std/zlib.d:(.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0x12a): undefined reference to `deflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib10UnCompress5errorMFiZv':
std/zlib.d:(.text._D3std4zlib10UnCompress5errorMFiZv[_D3std4zlib10UnCompress5errorMFiZv]+0x16): undefined reference to `inflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib10UnCompress6__dtorMFZv':
std/zlib.d:(.text._D3std4zlib10UnCompress6__dtorMFZv[_D3std4zlib10UnCompress6__dtorMFZv]+0x1c): undefined reference to `inflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib10UnCompress10uncompressMFAxvZAxv':
std/zlib.d:(.text._D3std4zlib10UnCompress10uncompressMFAxvZAxv[_D3std4zlib10UnCompress10uncompressMFAxvZAxv]+0xb3): undefined reference to `inflate'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/std/zlib.o): In function `_D3std4zlib10UnCompress5flushMFZAv':
std/zlib.d:(.text._D3std4zlib10UnCompress5flushMFZAv[_D3std4zlib10UnCompress5flushMFZAv]+0x84): undefined reference to `inflate'
std/zlib.d:(.text._D3std4zlib10UnCompress5flushMFZAv[_D3std4zlib10UnCompress5flushMFZAv]+0xbd): undefined reference to `inflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/etc/c/zlib.o): In function `deflateInit':
etc/c/zlib.d:(.text.deflateInit[deflateInit]+0xd): undefined reference to `deflateInit_'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/etc/c/zlib.o): In function `inflateInit':
etc/c/zlib.d:(.text.inflateInit[inflateInit]+0xd): undefined reference to `inflateInit_'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/etc/c/zlib.o): In function `deflateInit2':
etc/c/zlib.d:(.text.deflateInit2[deflateInit2]+0x18): undefined reference to `deflateInit2_'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/etc/c/zlib.o): In function `inflateInit2':
etc/c/zlib.d:(.text.inflateInit2[inflateInit2]+0xd): undefined reference to `inflateInit2_'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libphobos2-ldc.a(objects/etc/c/zlib.o): In function `inflateBackInit':
etc/c/zlib.d:(.text.inflateBackInit[inflateBackInit]+0xe): undefined reference to `inflateBackInit_'
collect2: error: ld returned 1 exit status

```

**Comment by rancidfrog** [comment]
I recommend use  DMD. 
ldc2 is less reliable when building tilix.

**Comment by gnunn1** [comment]
What version of ldc2 are you using, I'm building with 1.4.0

**Comment by pat-s** [comment]
@gnunn1 Also 1.4.0

@rancidfrog Haven't found dmd in the official repos. What is the exact name I have to look for?

**Comment by alexwhitman** [comment]
@pat-s You can download the deb from https://dlang.org/download.html

**Comment by rancidfrog** [comment]
https://www.archlinux.org/packages/community/x86_64/dmd/

**Comment by pat-s** [comment]
@alexwhitman that worked for me, thanks

However, now I'm stuck with https://github.com/gnunn1/tilix/issues/916.
Wanted to have 1.7.1 because of the Tab support but its not worth the work for it ;)

**Comment by alexwhitman** [comment]
Apply the patch in the first comment of #1166 and then it will build on 17.10.

**Comment by pat-s** [comment]
Thanks, worked! Now I'm stuck with https://github.com/gnunn1/tilix/issues/1213 :smile:
