### ISSUE TITLE
Unable to build current master

### ISSUE THREAD

**Issue by jerrycan321** [gnunn1/tilix#1724]
Using dmd-2.087.0 with:
dub build --build=release
(dmd-2.087.0)[jerome@sprat-localdomain tilix (master)]$ dub build --build=release
Performing "release" build using /home/jerome/dlang/dmd-2.087.0/linux/bin64/dmd for x86_64.
gtk-d:gtkd 3.8.5: target for configuration "library" is up to date.
gtk-d:vte 3.8.5: target for configuration "library" is up to date.
tilix ~master: building configuration "default"...
source/gx/gtk/util.d(155,5): Deprecation: foreach: loop index implicitly converted from size_t to int
source/gx/tilix/appwindow.d(1633,9): Deprecation: foreach: loop index implicitly converted from size_t to int
source/gx/tilix/colorschemes.d(213,67): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/colorschemes.d(213,67): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/colorschemes.d(221,77): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/colorschemes.d(221,77): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/colorschemes.d(224,71): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/colorschemes.d(224,71): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/colorschemes.d(227,69): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/colorschemes.d(227,69): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/colorschemes.d(230,67): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/colorschemes.d(230,67): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/session.d(915,70): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/session.d(915,70): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
source/gx/tilix/session.d(937,30): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/session.d(937,30): Deprecation: enum member `std.json.JSONType.FLOAT` is deprecated - Use .float_
source/gx/tilix/session.d(961,72): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/session.d(961,72): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
/home/jerome/dlang/dmd-2.087.0/linux/bin64/../../src/druntime/import/object.d(3453,36): Error: cannot implicitly convert expression aa of type shared(ProcessStatus[int]) to const(shared(ProcessStatus)[int])
source/gx/tilix/terminal/monitor.d(46,46): Error: template instance `object.values!(shared(ProcessStatus[int]), shared(ProcessStatus), int)` error instantiating
source/gx/tilix/terminal/regex.d(242,24): Deprecation: initialization of immutable variable from static this is deprecated.
source/gx/tilix/terminal/regex.d(242,24):        Use shared static this instead.
source/gx/tilix/terminal/regex.d(248,24): Deprecation: initialization of immutable variable from static this is deprecated.
source/gx/tilix/terminal/regex.d(248,24):        Use shared static this instead.
source/gx/tilix/terminal/terminal.d(2909,9): Deprecation: foreach: loop index implicitly converted from size_t to uint
source/gx/tilix/terminal/terminal.d(4104,62): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/terminal/terminal.d(4104,62): Deprecation: enum member `std.json.JSONType.FALSE` is deprecated - Use .false_
source/gx/tilix/terminal/terminal.d(4109,81): Deprecation: alias `std.json.JSON_TYPE` is deprecated - Use JSONType
source/gx/tilix/terminal/terminal.d(4109,81): Deprecation: enum member `std.json.JSONType.TRUE` is deprecated - Use .true_
/home/jerome/dlang/dmd-2.087.0/linux/bin64/dmd failed with exit code 1.
(dmd-2.087.0)[jerome@sprat-localdomain tilix (master)]$ 

Seem to see lots of deprecated warnings as well as the compile failures.

What version of the dmd compiler do folks here use to build the current Tilix here?

**Comment by f2404** [comment]
Builds fine with dmd 2.086.1 here:
```
$ dub build --build=release
Fetching gtk-d 3.8.5 (getting selected version)...
Performing "release" build using /usr/bin/dmd for x86_64.
gtk-d:gtkd 3.8.5: building configuration "library"...
../.dub/packages/gtk-d-3.8.5/gtk-d/generated/gtkd/glib/Spawn.d(305,3): Deprecation: foreach: loop index implicitly converted from size_t to int
gtk-d:vte 3.8.5: building configuration "library"...
tilix ~master: building configuration "default"...
source/gx/gtk/util.d(155,5): Deprecation: foreach: loop index implicitly converted from size_t to int
source/gx/tilix/appwindow.d(1633,9): Deprecation: foreach: loop index implicitly converted from size_t to int
source/gx/tilix/terminal/terminal.d(2909,9): Deprecation: foreach: loop index implicitly converted from size_t to uint
Linking...
```

**Comment by jerrycan321** [comment]
Thanks - I'll get that version of the D compiler and see if it changes anything.
J

**Comment by jerrycan321** [comment]
Well - that was it.
I installed dmd-2.086.1-0.fedora.x86_64.rpm and it all compiled as you said :-)
Many thanks for the quick response
J
